import React, {useEffect,useState} from 'react'
import {events,services,gallery,testimonials,packages,faqs} from './data/content'
const Arrow=()=> <span className="arrow">→</span>
const Btn=({children,outline=false})=><a href="#contact" className={`btn ${outline?'outline':'gold'}`}>{children}<Arrow/></a>
const Title=({kicker,children})=><div className="title"><p>{kicker}</p><h2>{children}</h2></div>
function Nav(){const [open,setOpen]=useState(false);const[down,setDown]=useState(false);useEffect(()=>{const f=()=>setDown(scrollY>20);addEventListener('scroll',f);return()=>removeEventListener('scroll',f)},[]);return <header className={down?'down':''}><a className="brand" href="#home">EVENT<span>AURA</span></a><nav className={open?'open':''}>{['Home','About','Services','Events','Gallery','Packages','Testimonials','Contact'].map(x=><a key={x} onClick={()=>setOpen(false)} href={'#'+x.toLowerCase()}>{x}</a>)}</nav><a className="mini-cta" href="#contact">Plan Your Event</a><button className="hamburger" aria-label="Menu" onClick={()=>setOpen(!open)}>☰</button></header>}
function Hero(){return <section id="home" className="hero"><div><p>Beautifully Planned. Effortlessly Celebrated.</p><h1>Where Every Moment<br/><em>Becomes a Memory.</em></h1><p className="copy">From intimate celebrations to unforgettable weddings, EventAura brings your vision to life with elegance, creativity and attention to every detail.</p><Btn>Plan Your Event</Btn><a className="hero-link" href="#services">Explore our services</a></div></section>}
function Intro(){return <section id="about" className="intro section"><img src="https://images.unsplash.com/photo-1507504031003-b417219a0fde?auto=format&fit=crop&w=1000&q=85" alt="Elegant dinner table setting"/><div><p className="kicker">The EventAura difference</p><h2>Celebrations,<br/><em>Beautifully Crafted.</em></h2><p>At EventAura, we believe every celebration deserves to be extraordinary. From the first idea to the final guest departure, we create memorable experiences that reflect your personality, style and story.</p><a className="text" href="#story">Discover EventAura <Arrow/></a></div></section>}
function Events(){return <section id="events" className="section cream"><Title kicker="Made for every milestone">Celebrate Every <em>Occasion</em></Title><div className="cards">{events.map(e=><article key={e.title}><img src={e.image} alt={e.title} loading="eager"/><div><small>{e.category}</small><h3>{e.title}</h3><span>Explore <Arrow/></span></div></article>)}</div></section>}
function Services(){return <section id="services" className="section"><Title kicker="Our expertise">What We <em>Do</em></Title><div className="services">{services.map((s,i)=><article key={s}><b>0{i+1}</b><i>✦</i><h3>{s}</h3><p>Thoughtfully considered expertise for celebrations that feel wholly yours.</p><a href="#contact">Learn more <Arrow/></a></article>)}</div></section>}
function Portfolio(){return <section className="portfolio section"><Title kicker="A glimpse into our world">Moments We've <em>Created</em></Title><div>{events.slice(0,6).map(e=><article key={e.title}><img src={e.image} alt={e.title} loading="eager"/><span><small>{e.category}</small><h3>{e.title}</h3><p>{e.description}</p><a href="#gallery">View event <Arrow/></a></span></article>)}</div><Btn outline>View all events</Btn></section>}
function Why(){let x=[['✦','Creative Vision','Beautiful concepts thoughtfully designed around your story.'],['⌁','Attention to Detail','Because the smallest details create the biggest memories.'],['○','Seamless Planning','We handle the details so you can enjoy the moment.'],['♡','Unforgettable Experiences','Every celebration is designed to leave a lasting impression.']];return <section className="why"><div><p className="kicker">Why EventAura?</p><h2>Every detail,<br/><em>thoughtfully yours.</em></h2><p>We combine inspired creativity with flawless coordination, making the journey to your celebration as beautiful as the day itself.</p><Btn outline>Begin your story</Btn></div><aside>{x.map(a=><article key={a[1]}><i>{a[0]}</i><h3>{a[1]}</h3><p>{a[2]}</p></article>)}</aside></section>}
function Process(){return <section className="section process"><Title kicker="Our process">Your Celebration, <em>Simplified.</em></Title><div>{[['01','Share your vision','Tell us what you’re dreaming of.'],['02','Plan together','We create a personalized event concept.'],['03','We bring it to life','Our team coordinates the details.'],['04','Celebrate','Relax and enjoy your special day.']].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>}
function Gallery(){const[f,setF]=useState('All'),[n,setN]=useState(null);let list=f==='All'?gallery:gallery.filter(x=>x.category===f);useEffect(()=>{let x=e=>{if(n===null)return;if(e.key==='Escape')setN(null);if(e.key==='ArrowRight')setN((n+1)%list.length);if(e.key==='ArrowLeft')setN((n-1+list.length)%list.length)};addEventListener('keydown',x);return()=>removeEventListener('keydown',x)},[n,list.length]);return <section id="gallery" className="gallery section"><Title kicker="The EventAura journal">An Archive of <em>Joy</em></Title><div className="filters">{['All','Weddings','Birthdays','Anniversaries','Christenings','Engagements','Corporate'].map(x=><button className={f===x?'selected':''} onClick={()=>setF(x)} key={x}>{x}</button>)}</div><div className="masonry">{list.map((g,i)=><button key={i} onClick={()=>setN(i)}><img src={g.image} alt={g.title} loading="eager"/><span>{g.category}<b>View moment ↗</b></span></button>)}</div>{n!==null&&<div className="lightbox" role="dialog" aria-modal="true"><button className="close" onClick={()=>setN(null)}>×</button><button className="prev" onClick={()=>setN((n-1+list.length)%list.length)}>←</button><img src={list[n].image} alt={list[n].title}/><button className="next" onClick={()=>setN((n+1)%list.length)}>→</button><p>{n+1} / {list.length}</p></div>}</section>}
function Testimonials(){const[n,setN]=useState(0);useEffect(()=>{let x=setInterval(()=>setN((n+1)%testimonials.length),5500);return()=>clearInterval(x)},[n]);let t=testimonials[n];return <section id="testimonials" className="testimonials"><p className="kicker">Kind words</p><h2>What Our Clients <em>Say</em></h2><i>“</i><div><b>★★★★★</b><blockquote>{t[2]}</blockquote><p><strong>{t[0]}</strong><span>{t[1]}</span></p></div><aside>{testimonials.map((_,i)=><button onClick={()=>setN(i)} className={n===i?'on':''} aria-label={'Testimonial '+(i+1)} key={i}/>)}</aside></section>}
function Packages(){return <section id="packages" className="section"><Title kicker="Created around you">Choose Your Celebration <em>Package</em></Title><div className="packages">{packages.map((p,i)=><article className={i===1?'hot':''} key={p[0]}>{i===1&&<label>Most loved</label>}<p>{p[0]}</p><h3>{p[1]}</h3><span>Designed for a thoughtful, joyful occasion.</span><ul>{p[2].map(x=><li key={x}>✓ {x}</li>)}</ul><Btn outline>Get started</Btn></article>)}</div><div className="custom"><div><p className="kicker">Something entirely yours</p><h3>Imagine it. We'll make it happen.</h3></div><p>Tell us what you envision and we'll create a celebration around it.</p><Btn>Request a custom plan</Btn></div></section>}
function Story(){return <section id="story" className="story section"><div><p className="kicker">Our story</p><h2>More Than Events.<br/>We Create <em>Memories.</em></h2><p>EventAura is a collective of dreamers, designers and detail-lovers who see every occasion as an opportunity to make someone feel deeply celebrated.</p><aside>{['Creativity','Excellence','Integrity','Personalization','Attention to Detail'].map(x=><span key={x}>✦ {x}</span>)}</aside></div><img src="https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=1000&q=85" alt="Elegant wedding reception" loading="lazy"/></section>}
function FAQ(){const[n,setN]=useState(0);return <section className="faq section"><Title kicker="Questions, answered">Everything you need to <em>know</em></Title><div>{faqs.map((q,i)=><article key={q}><button onClick={()=>setN(n===i?-1:i)}>{q}<b>{n===i?'−':'+'}</b></button>{n===i&&<p>We would be delighted to discuss this with you. Each EventAura experience is created around your needs, vision and celebration.</p>}</article>)}</div></section>}
function Contact(){const[sent,setSent]=useState(false);return <><section className="cta"><div><p>YOUR NEXT BEAUTIFUL MOMENT</p><h2>Your Celebration<br/>Starts <em>Here.</em></h2><span>Whatever the occasion, let’s create something unforgettable.</span><br/><Btn>Plan my event</Btn></div></section><section id="contact" className="contact section"><div><p className="kicker">Get in touch</p><h2>Let's Create Something <em>Beautiful.</em></h2><p>Tell us about the occasion you’re dreaming of. We’ll be in touch within two business days.</p><small>hello@eventaura.co<br/>+233 24 555 0148<br/>Accra, Ghana · Available worldwide</small></div><form onSubmit={e=>{e.preventDefault();setSent(true);e.target.reset()}}>{['Full Name','Email','Phone'].map(x=><label key={x}>{x}<input required type={x==='Email'?'email':'text'} placeholder={'Your '+x.toLowerCase()}/></label>)}<label>Event Type<select defaultValue="" required><option value="" disabled>Select an occasion</option>{events.map(x=><option key={x.title}>{x.category}</option>)}</select></label><label>Preferred Date<input type="date"/></label><label className="wide">Tell us a little more<textarea required rows="4" placeholder="Your vision, guest count, location..."/></label><button className="btn gold">Get in touch <Arrow/></button>{sent&&<p className="success">Thank you! We've received your message and will be in touch soon.</p>}</form></section></>}
function Footer(){return <footer><div><section><a className="brand" href="#home">EVENT<span>AURA</span></a><p>Where Every Moment Becomes a Memory.</p></section><section><b>Explore</b>{['About','Services','Events','Gallery','Packages','Contact'].map(x=><a href={'#'+x.toLowerCase()} key={x}>{x}</a>)}</section><section><b>Stay inspired</b><p>Notes on beautiful celebrations, delivered occasionally.</p><form><input placeholder="Your email address" aria-label="Email address"/><button>→</button></form></section></div><small>© 2026 EventAura. All Rights Reserved. <span>Instagram · Facebook · Pinterest</span></small></footer>}
export default function App(){return <><Nav/><main><Hero/><Intro/><Events/><Services/><Portfolio/><Why/><Process/><Gallery/><Testimonials/><Packages/><Story/><FAQ/><Contact/></main><Footer/></>}
